### ISSUE TITLE
Deploy changes to policy files to whatwg.org

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#110]
Currently it's the build/deploy step of https://github.com/whatwg/whatwg.org that converts the Markdown files in this repository to HTML and publishes it to whatwg.org. It works when it runs, but updating just the files in this repo doesn't trigger that deploy process.

See https://github.com/whatwg/sg/pull/88#issuecomment-596986927 for a recent example.

**Comment by annevk** [comment]
Given that there's a human involved in merging PRs, going to https://github.com/whatwg/whatwg.org/commits, clicking the checkmark, going to the Travis CI build, and rerunning it, doesn't seem overly onerous given the number of changes.

It might help to see a diff of the generated HTML though in case of further Markdown/CommonMark issues.

**Comment by annevk** [comment]
I suspect this can be fixed more easily after https://github.com/whatwg/meta/issues/173 (at least the part of sg changing causing whatwg.org to rerun).

**Comment by foolip** [comment]
After I landed https://github.com/whatwg/sg/pull/129 I tried to get it deployed by restarting the latest workflow run on push to master, which resulted in https://github.com/whatwg/whatwg.org/runs/779420751?check_suite_focus=true

However, that doesn't seem to have worked, and I don't know why. If merging https://github.com/whatwg/whatwg.org/pull/333 also doesn't deploy the changes then something weird is going on.

**Comment by foolip** [comment]
Oops, false alarm, I had an entry in my /etc/hosts for whatwg.org for testing https://github.com/whatwg/misc-server/pull/129.
