### ISSUE TITLE
Policy Change: define the policy update process

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#116]
https://github.com/whatwg/sg/issues/114 is the first update of our policies since the initial formation of the WHATWG SG. We've used the mechanism described in [entity-agreement-success.hbs](https://github.com/whatwg/participate.whatwg.org/blob/bf3006bb2c6c0728ce3591ce29a7cbf2396ff68f/views/entity-agreement-success.hbs#L19) / [individual-agreement-success.hbs](https://github.com/whatwg/participate.whatwg.org/blob/bf3006bb2c6c0728ce3591ce29a7cbf2396ff68f/views/individual-agreement-success.hbs#L21) on participate.whatwg.org and used a 45 day notification period.

We'd like to define this process a bit more clearly:
- Hoist these bits into https://whatwg.org/policies or one of the pages it links
- In that same place, write down the 45 day notice

This issue itself is *not* the notification of the changes as it doesn't start with "Policy Change:", just the starting point for discussing the change.

Here's the wording from [individual-agreement-success.hbs](https://github.com/whatwg/participate.whatwg.org/blob/bf3006bb2c6c0728ce3591ce29a7cbf2396ff68f/views/individual-agreement-success.hbs#L21):

<blockquote>
<p>Notifications of WHATWG policy changes and of any <a href="https://whatwg.org/workstream-policy#review-draft">Review Draft</a> publications will be through GitHub issues and pull requests, which you can subscribe to by <a href="https://help.github.com/articles/watching-and-unwatching-repositories/">watching</a> appropriate repositories.

<p>To be notified of upcoming changes to WHATWG Policies, watch the <a href="https://github.com/whatwg/sg">whatwg/sg</a> repository; this is where WHATWG policies are maintained.

<p>To be notified when a Review Draft is published, watch the workstream repository for that Living Standard.

<p>Watching these repositories will generate many notifications related to ongoing WHATWG governance and standardization work, but you can filter using the subject-line prefixes "Policy Change:" or "Review Draft Publication:" if those specific events are all you are interested in.

<p>If you do not watch these repositories, you might miss important notifications that affect participation in the WHATWG. The notices generated by the repository are the only notices that the WHATWG will regularly provide regarding issues and pull requests (including changes to WHATWG policies and the posting of Review Drafts).
</blockquote>

**Comment by foolip** [comment]
At same same time, we might as well pull out the "Review Draft Publication:" bit, which isn't about updating policies, but makes sense to be part of a policy, probably.

**Comment by othermaciej** [comment]
I suggest we discuss this in our next meeting. Both what the update policy should be, and how/where we should document it.

**Comment by othermaciej** [comment]
Our rough consensus is that we want to provide a 45-day notice period via an open Pull Request for most changes tot he IPR Policy (with rooms for exception in urgent cases) and to major changes to the other policies (so there's no delay on minor and uncontroversial changes). We should document this in the SG Policy and possibly in the participation agreements?

**Comment by foolip** [comment]
What we are missing now is a concrete proposal for review. I'll self-assign, but don't expect I will get to this very soon. If anyone else wants to give it a try, feel free to take it from me :)

**Comment by davidru** [comment]
The Legal Committee wanted to check the status of formalizing the 45 day notice period?
