### ISSUE TITLE
[Minutes] SG Meeting 2020-04-20

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#117]
The SG has now set up bi-weekly meetings, and this was the first such meeting. @dbaron took notes for this meeting (thanks!) and I am just posting them here.

## issues/PRs in whatwg/sg repository

@foolip: have we ever been good at issue triage?

@dbaron / @travisleithead: no

@othermaciej: we can fall back to issue/PR triage as the fallback agenda topic for this standing meeting

@travisleithead: run through repos as to what we should be watching?

  sg
  participant-data?
  participant-data-private?
  meta?
  sg-editors-private

@dbaron: @annevk and @domenic seem to handle participant-data issues.

@foolip: others can handle meta

@othermaciej: sg-editors-private is a way for us to speak to editors privately.  But shouldn't be issues to resolve; just a discussion board.

@dbaron: probably use it a bit more

@foolip: should we close issues

@othermaciej: if they're no longer relevant, we should close.  So we should watch this one.

## Merging PRs

@foolip: What's the approval threshold for merging PRs in sg repo?

@othermaciej: for substantive policy changes we require supermajority, but editorial one approval is probably enough.  So for editorial the approver could state that it's editorial and doesn't need approvals from others.

@foolip: wait for the fourth?

@othermaciej: nice... but hopefully if it's substantive we've already discussed prior to approvals.

## PRs https://github.com/whatwg/sg/pull/111 and https://github.com/whatwg/whatwg.org/pull/303

@othermaciej: this `db.json` file has both workstreams and some other things that aren't in worktreams (`biblio`)

(reading of the diff)

@othermaciej: Would be nice to look over the generated info to make sure it's the same and it's readable.  If that's true it seems like it's editorial.

@foolip: I can review these 2 PRs, put up /workstreams on the real site from the generation code.

## Conclusion

@othermaciej: Can keep going with agenda at next meeting in 2 weeks, go through remaining PRs.  And maybe we can use github assignees to mark who's dealing with things.

@foolip: I will review these 2 PRs.

**Comment by dbaron** [comment]
It's also worth noting explicitly (as mentioned at the very start of this issue) that the SG agreed to meet every other week at 14:00 California time on Mondays so that we'd make more progress on our backlog of stuff.
