### ISSUE TITLE
Allowing trivial contributions without signing the contributor agreement

### ISSUE THREAD

**Issue by bakkot** [whatwg/sg#121]
Forgive me if this was raised previously, or should be raised elsewhere; I didn't see anything obvious.

I am working on getting my employer, F5 networks, to sign the contributor agreement so that I can submit PRs. As I'm sure you know, that's not a trivial process at an organization of any size, and I'm not even sure they'll be willing to do so. Even if we do, that's likely to involve conversations with a lawyer, building out a process to get people added our Github org, etc.

Given that the PRs I have thus far wanted to contribute are entirely trivial bugfixes - e.g. [this](https://github.com/whatwg/html/pull/5406) or [this](https://github.com/whatwg/streams/pull/941) - it feels like signing this agreement not a good use of anyone's time (as has been [pointed out before](https://github.com/whatwg/sg/issues/67#issuecomment-415685378)).

I'm still trying to go about getting the agreement signed, because I would like for myself and my coworkers to be able to contribute such PRs and also potentially more substantive ones, but while we're going about that I wondered if it might be possible to route around the issue by changing the process so that trivial PRs could be accepted without this rigamarole. W3C has a process by which non-substantive PRs can be manually marked as such, which has allowed [me](https://github.com/w3c/webrtc-pc/pull/2112#issuecomment-469430405) and [others](https://github.com/WICG/import-maps/pull/196#issuecomment-574277280) to contribute such trivial changes to specs under that organization, and perhaps WHATWG could adopt something similar.

**Comment by KiChjang** [comment]
See #63 for some context around approving non-normative changes.

**Comment by bakkot** [comment]
Ah, thanks, not sure how I missed that issue. I guess I'll just close this and add my concrete examples there.
