### ISSUE TITLE
Clarify "automated decision-making" in privacy policy

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#123]
https://github.com/whatwg/sg/pull/120, concerning our website whatwg.org, uses the phrasing "It does not use other tracking technologies and it does not use automated decision-making."

For a layperson, this not easy to interpret, as pointed out by @domenic in https://github.com/whatwg/sg/pull/120#discussion_r416843033.

I speculated that it's in reference to GDPR, but have since learned that the wording is intended to not *only* be about GDPR, but also other privacy regulation.

We should clarify this wording, and @othermaciej had some ideas here.

**Comment by othermaciej** [comment]
I think [Apple's Privacy Policy](https://www.apple.com/legal/privacy/en-ww/) has some good wording here:

> **The Existence of Automated Decision-Making, Including Profiling**
> Apple does not take any decisions involving the use of algorithms or profiling that significantly affect you.

Google, Microsoft, Mozilla, W3C, and IETF privacy policies do not appear to use the exact phrase "automated decision-making".

**Comment by foolip** [comment]
@othermaciej has volunteered to suggest a wording for this in a PR.

**Comment by annevk** [comment]
I created #160 to address this per the wording in Maciej's comment above.
