### ISSUE TITLE
Notice for Living Standards

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#124]
Our [workstream policy](https://github.com/whatwg/sg/blob/961c2712422bf3efa446072520cdd048fff726c6/Workstream%20Policy.md#notice-for-living-standards) says:

> For each Living Standard that has had at least one Review Draft published, it must also include the following notice:
> > This is the Living Standard. Those interested in the patent-review version should view the Living Standard Review Draft.

It looks like we haven't implemented this. Filing an issue here to keep track of it, although implementation would likely be in build tools.

@whatwg/editors for ideas about how to implement this.

**Comment by annevk** [comment]
Thoughts:

1. We create a new piece of Bikeshed metadata whose value is the YYYY-MM value of the latest RD.
2. We ensure that `make review` updates that value and fails if it is missing.
3. We update Bikeshed's WHATWG boilerplate generation to include a new section if that value is given.
   1. I'm not sure where, would an appendix be acceptable?

**Comment by domenic** [comment]
That tooling makes sense, although for new LSs with no RD date metadata, I'm not sure if Bikeshed has the necessary power in its macro language to do conditionals. Hmm.

I always pictured this statement living next to the copyright in the acknowledgments.

**Comment by annevk** [comment]
So should we have two statuses then? LS-EARLY and LS? (There are indeed no conditionals.)

Bikeshed: "Intellectual Property Rights" (includes copyright and it's better not introduce novel abbreviations).

**Comment by domenic** [comment]
That seems somewhat reasonable, although I worry that it would result in us having to duplicate a number of Bikeshed files into LS- and LS-EARLY versions. It might be better if we could get some sort of conditional support in Bikeshed, or more generally, just ask for @tabatkins's opinion on the best way forward.

**Comment by tabatkins** [comment]
Yeah, I haven't ever added conditionals to macros yet (but there've been other requests for it, so maybe).

But I can also just specially handle this case for y'all.

**Comment by annevk** [comment]
Thanks to @tabatkins's work on Bikeshed I've been able to make progress on this:

1. https://github.com/tabatkins/bikeshed/pull/1726 enables drafts to define a LATESTRD text macro with YYYY-MM as value.
2. Next would be adding that LATESTRD text macro to all our drafts and ensure that review.sh on whatwg.org updates it whenever we publish a new Review Draft. (This can effectively reuse a lot of logic from the work done on HTML that is referenced below.)

And HTML which has a non-Bikeshed build was tackled in https://github.com/whatwg/html/pull/5697.

I'll close this when that's all done. Let me know if you have concerns or questions.

**Comment by annevk** [comment]
Apart from two documents (console & fullscreen) this is now done. `make review` will also update the field each time it is run (whenever we decide to create a new Review Draft).

The only thing that is not semi-automated is when a standard has its first Review Draft published, but that is a pretty rare event.
