### ISSUE TITLE
Citizen Code of Conduct link is dead

### ISSUE THREAD

**Issue by Jayman2000** [whatwg/sg#152]
The WHATWG Code of Conduct links to https://citizencodeofconduct.org/. That website is down, and it seems like it's down permanently. The [latest snapshot on the Wayback Machine](https://web.archive.org/web/2020*/https://citizencodeofconduct.org/) is about 9 months old, and I found [an issue](https://github.com/stumpsyn/policies/issues/29) that implies that this isn't a temporary outage.

**Comment by TimothyGu** [comment]
The Rust Code of Conduct (on which the WHATWG one is based) now links to https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md

**Comment by annevk** [comment]
Thanks for reporting this. I've reached out to some of the people involved in that issue to see if it can be remedied. Following Rust again seems reasonable, though we might want to look into a longer term fix if that is basically no longer maintained.

**Comment by annevk** [comment]
I wonder if instead we could instead expand harassment inline, e.g.:

> harassment includes, but is not limited to, offensive verbal comments related to gender, gender identity and expression, age, sexual orientation, disability, physical appearance, body size, race, ethnicity, religion, and technology choices, sexual images in public spaces, deliberate intimidation, stalking, doxing, following, inappropriate photography or recording, inappropriate physical contact, unwelcome sexual attention, sustained disruption of events, as well as advocating for or encouraging harassment.

That's based on https://github.com/stumpsyn/policies/blob/master/citizen_code_of_conduct.md#4-unacceptable-behavior and https://confcodeofconduct.com/.

**Comment by travisleithead** [comment]
@annevk your suggested text above looks like a good replacement for the link. I'm in favor of replacing the link with the content.

**Comment by annevk** [comment]
I created #156 to address this.
