### ISSUE TITLE
Request for Workstream Participant Invitation status

### ISSUE THREAD

**Issue by dontcallmedom** [whatwg/sg#157]
I would like to request Invited Participation status to the WHATWG workstreams.

I've tried but failed to get my employer (ERCIM) to join WHATWG as an organization. ERCIM, as one of the 4 W3C hosts, has significant investment in the field of business technologies. Conversely, as an employee of a W3C hosts, none of my contributions in my W3C work are expected to be covered by non-RF terms.

Based on my work in reffy and associated tools, there are a number of improvements that I have tried pushing in WHATWG specs but where my lack of workstream participant status made difficult. I would like to be in a position to contribute to all WHATWG workstreams without that barrier; if a smaller scope invitation is preferable, I would want to start at least with the HTML spec.

**Comment by foolip** [comment]
Hi @dontcallmedom, nice to see you here! This is our first such request :)

The SG will get together and discuss and get back to you here or in private. Since it's the first time I don't dare promise a timeline, but I'll try my best to move it along.

**Comment by foolip** [comment]
Hi @dontcallmedom! Sorry it took a while, but we now have all the information we need, and are ready to grant your request.

In order to not speak on behalf of anyone else, I'll give the 👍 for Google, and allow @annevk @othermaciej and @travisleithead to speak on behalf of Mozilla, Apple and Microsoft.

**Comment by annevk** [comment]
All good from our side. Looking forward to your contributions!

**Comment by travisleithead** [comment]
Excited to have you join us! 👍for Microsoft

**Comment by othermaciej** [comment]
+1 on behalf of Apple.

**Comment by annevk** [comment]
Hurray!

@dontcallmedom next step here is for you to fill out https://participate.whatwg.org/agreement and select "I am invited by the Steering Group and want to join all the Workstreams to which I have been invited." Then when you want to land a PR one of us will verify you. Starting the moment you sign it should all be in order for the next 36 months at which point we can extend it assuming circumstances haven't changed.

Let us know if you have any questions and thanks for joining.

**Comment by dontcallmedom** [comment]
thank you all for getting this through!

I've now filled the agreement, and will be able to restart work on some of my pending pull requests :)

**Comment by foolip** [comment]
Welcome, @dontcallmedom!

@whatwg/sg @domenic I've filed https://github.com/whatwg/participate.whatwg.org/issues/190 about encoding the 36 months in our tooling.
