### ISSUE TITLE
New standard: File System

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#176]
In a TPAC 2021 breakout session we discussed standardizing [OPFS](https://wicg.github.io/file-system-access/#sandboxed-filesystem) + [AccessHandle](https://github.com/WICG/file-system-access/blob/main/AccessHandle.md): https://docs.google.com/document/d/1RBK5pshKiKWa0drPEPrYwsAmZUELO_23hGM2iJTFiJA/edit. It's essentially a new storage API like IndexedDB, but with a file system API. The infrastructure it provides will be so it can also be used to support native file system access, but that will not be part of this standard and as such cannot be mandated from implementations.

@mkruisselbrink will be the editor. I will help with the transition.

A question the SG needs to address is whether this warrants a new Workstream or can be placed under an existing Workstream, such as Storage. The latter seems slightly preferable as it would keep things simple. (The whole thing sits on top of `StorageManager`.)

I suggest "File System" as name and "fs" as shortname.

**Comment by foolip** [comment]
Here's the current scope of the Storage workstream:
https://github.com/whatwg/sg/blob/7c5b48ae1a57b92ad88c4ce7601c39298e34b7ac/db.json#L372

**Comment by annevk** [comment]
We (@whatwg/sg except for @othermaciej) had a discussion about this and considered this to be in scope for the Storage Standard. These seem to be the relevant bits from the Workstream Policy on this question:

> Each Workstream is dedicated to a single Living Standard (or, if unavoidable, two or more inextricably interdependent Living Standards)

&mdash; https://whatwg.org/workstream-policy#workstream-living-standards

Given that it builds directly on `StorageManager` as well as the underlying infrastructure this seems met. The reason we'll keep it separate is because it will have its own editor.

> Within the approved Workstream Scope, the Editor evolves the Living Standard and other publications of the Workstream. The Workstream's Editor may add, remove, merge or split Living Standards and other associated documents, so long as all deliverables are still within the Workstream's Scope. If the change affects Living Standards, the Editor must notify the Steering Group 14 Days in advance of the change.

&mdash; https://whatwg.org/workstream-policy#editor-discretion

This suggests this addition should be okay starting tomorrow, roughly.

If anyone has any further feedback on this, nowish would be a good time.

**Comment by othermaciej** [comment]
Retroactively, I'll add that it seems ok to me to add this as an additional spec in the Storage Workstream and a suitable 14 days notice has been given.

**Comment by annevk** [comment]
A preview can now be found at https://whatpr.org/fs/1.html.

**Comment by foolip** [comment]
@annevk should we file an issue at https://github.com/w3c/whatwg-coord/issues?

**Comment by annevk** [comment]
FYI: once https://github.com/whatwg/fs/pull/1 is merged the standard will be live.
