### ISSUE TITLE
Email to sg@whatwg.org is likely to be classified as spam

### ISSUE THREAD

**Issue by foolip** [whatwg/sg#187]
Emailing sg@whatwg.org isn't a reliable way of getting in touch with the Steering Group, because the email is too likely to be classified as spam. The most recent example I just found going through the spam-classified email is "Question about boolean attribute", which is *not* spam. This isn't the first such case.

I believe the issue is that we get lots of spam to sg@whatwg.org, but only very rarely "real" email. There hasn't been enough real email for at least my spam filter to learn from, and we don't expect to get a lot of email in general, so this will remain the case.

@annevk @othermaciej @travisleithead did any of you see "Question about boolean attribute", or did that get stuck in your spam filters too?

Note that there's also a spam filter on the email provider side before the forwarding, anything that gets stuck there isn't going to reach any of us. There's even more spam there, and I haven't looked through it.

**Comment by annevk** [comment]
It was in my spam folder. I have attempted to teach the spam filter.

**Comment by foolip** [comment]
Thanks @annevk for confirming, and I didn't know that spam would get forwarded, I assumed not. I guess it's good in a way that it does. But also bad that we all individually need to train our filters, and that it won't transfer is an SG rep changes.

I've now replied to that question, which may have influenced the spam detection for the others in the SG.

**Comment by foolip** [comment]
Unfortunately, I don't have any great ideas for how to improve this. The only thing that comes to mind would be to make a habit of going over all spam-classified SG email every 2 weeks and looking for non-spam, and repeating that until the problem hasn't occurred in a long time. The problem is that the expected amount of email to the SG is very low, zero in a year wouldn't be a huge outlier even if we've had a few in 2021.

**Comment by annevk** [comment]
Going through the email occasionally seems okay. I just went through everything at the email provider. Scanned all spam and cleared the inbox.

**Comment by foolip** [comment]
Thanks @annevk! How far back did you go, and roughly how much time did it take you? I guess no new non-spam found?

**Comment by annevk** [comment]
I went through everything addressed to our email address that was there. Maybe 20 minutes? Some other email conversations we had were also classified as spam (perhaps partially) and I unmarked those as well.

**Comment by foolip** [comment]
OK, I'm going to add a calendar reminder to do the same thing again in a month, and I'll report back here then.

**Comment by foolip** [comment]
I have just stepped through all of the spam-classified email since Dec 20 without finding more non-spam email. I'll set a reminder to do it again in two months and report back here then.

**Comment by cvrebert** [comment]
@foolip Any misclassified ham in the intervening ~1.5 years? Any need to worry about auto-deletion of old messages in Spam?

**Comment by foolip** [comment]
I have handed over the account to @cwilso. Chris, is there still a problem from the point of view of the SG?

**Comment by cwilso** [comment]
I just walked through several months worth and found nothing misclassified.  I'll set a reminder to do so again in a couple of months and then set it to auto-delete and close this issue.

**Comment by cwilso** [comment]
I just went through all the last two months; no misclassified spam.  I set it to auto-delete spam after 31 days.
