### ISSUE TITLE
Consider acknowledging the HTML Standard triage meeting in Working Mode

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#196]
Thanks to @past the HTML Workstream has a regular meeting (monthly) that's organized through the whatwg/html repository. This should be perhaps be acknowledged in Working Mode as it currently indicates there are no regular meetings.

As a start we could replace

> The WHATWG doesn't generally run any regular meetings.

with

> Most Workstreams don't run any regular meetings.

**Comment by travisleithead** [comment]
This sounds like a great idea!
