### ISSUE TITLE
[Participant Agreement] Employment change

### ISSUE THREAD

**Issue by nicolo-ribaudo** [whatwg/sg#197]
Hi!

I recently started working as a contractor for @igalia, which signed the agreement as an entity. Do I have to "unsign" the participant agreement, that I signed as an individual before this change?

**Comment by annevk** [comment]
Yeah, if you're willing to submit a PR to remove your own entry from https://github.com/whatwg/participant-data that would be great. See https://github.com/whatwg/participant-data/commit/e1da0fa6a083e9a5808e591a363dbafc3c535d5c for an example.
