### ISSUE TITLE
Update editor of whatwg/fs

### ISSUE THREAD

**Issue by a-sully** [whatwg/sg#206]
I'm proposing to replace @mkruisselbrink (a.k.a. Marijn Kruisselbrink, mek@chromium.org) as editor of the File System Standard. Marijn has mostly moved on from the project, and I'll also be taking ownership of the corresponding https://github.com/WICG/file-system-access specification.

Current:
https://github.com/whatwg/sg/blob/f4fdd987790ecba4aecc2f8ab0dd2121f76fc172/db.json#L401-L406

Proposed:
```
          "authors": [
            {
              "name": "Austin Sullivan",
              "email": "asully@chromium.org"
            }
          ],
```

**Comment by annevk** [comment]
Thanks @mkruisselbrink for your efforts and @a-sully for willing to continue them! (And all the contributions you have already made!)

I suspect the SG will be able to confirm this next week Wednesday at the latest, but with a thumbs up from @tantek and @bmathwig we might get there a little earlier.

@a-sully would you be willing to create a PR for `db.json`?
