### ISSUE TITLE
Ensure the W3C MoU doesn't need changes post-W3C LE transition

### ISSUE THREAD

**Issue by cwilso** [whatwg/sg#209]

**Comment by cwilso** [comment]
In reviewing https://www.w3.org/2019/04/WHATWG-W3C-MOU.html, it seems like this isn't really a problem: the MoU does not refer to MIT, it refers to "W3C".  Should confirm with legal.

**Comment by michaelchampion** [comment]
> the MoU does not refer to MIT, it refers to "W3C".

That was Ralph Swick's (W3C Interim CEO)'s assessment too, FWIW. https://lists.w3.org/Archives/Member/w3c-ac-forum/2023JanMar/0081.html
