### ISSUE TITLE
New standard: URLPattern

### ISSUE THREAD

**Issue by sisidovski** [whatwg/sg#215]
Based on the discussion at the TPAC 2023 and follow ups, we’ll propose standardizing URLPattern API.

[URLPattern](https://wicg.github.io/urlpattern/) is the API providing a web platform primitive for matching URLs. The pattern syntax is adopted from the popular [path-to-regexp](https://github.com/pillarjs/path-to-regexp) javascript library and is more ergonomic than using regular expressions.

@jeremyroman and @sisidovski will edit the spec, who took over the work from @wanderview. 

Some questions to the sg:
- @annevk suggested putting this proposal into the [URL workstream](https://whatwg.org/workstreams#url). Does that work for the rest of the SG?
- Do we have anything to resolve on our side before moving to WHATWG?
- Can we transfer the existing https://github.com/WICG/urlpattern repository into the WHATWG org?

For the short name, I feel just using “urlpattern” is fine. We suggest using a "*" in a circle as the icon.

**Comment by annevk** [comment]
https://github.com/whatwg/meta/blob/main/NEW-STANDARD.md has a checklist to go over. 2 might be an item you'd be willing to cover @sisidovski? I think @domenic was willing to help with the remainder. I'd be happy to review.

To transfer the repository it might make the most sense to move it to @domenic and then he can move it further. From experience GitHub will handle the redirects across.

**Comment by cwilso** [comment]
I was talking with @foolip about this.  Unfortunately, the github.com references will redirect, but the github.io hosting won't.

**Comment by jyasskin** [comment]
We can make the github.io hosting redirect too, by imitating https://github.com/WICG/wicg.github.io/blob/main/picture-in-picture/index.html.

**Comment by sisidovski** [comment]
Thank you all!

> https://github.com/whatwg/meta/blob/main/NEW-STANDARD.md has a checklist to go over. 2 might be an item you'd be willing to cover @sisidovski? I think @domenic was willing to help with the remainder. I'd be happy to review.

Yes. Now I'm working on the logo work. Should I also work on 4?

**Comment by domenic** [comment]
A pull request for 4 would be appreciated, but there is no urgency since we will not want to merge it until we have also completed 1.

The only field that might not be obvious is `review_draft_schedule`. That is two months of the year review drafts are generated. It looks like we are load balancing between (1, 7), (2, 8), and (3, 9), so pick whichever of those has the fewest specs currently.

**Comment by annevk** [comment]
(3, 9) is the one we want so it would join "WHATWG RDs (4)" (for those on the Review Draft calendar invite).

The next standard we add will require a new calendar entry if we stick to publishing about 5 a month. (There's also (6, 12), so we're up to 20 standards including this one.)

**Comment by annevk** [comment]
Just wanted to note that the SG discussed this briefly yesterday and from the SG's perspective all is in order here. Technically this is a Workstream editor decision, but the SG appreciates the heads up as it also involves changes to `db.json` and derivative documents the SG is responsible for.

**Comment by domenic** [comment]
I've made some progress on [the checklist](https://github.com/whatwg/meta/blob/main/NEW-STANDARD.md):

- Subdomain works, https://urlpattern.whatwg.org/
- Twitter account exists, [urlpatternapi](https://twitter.com/urlpatternapi). (I want to rename to `urlpatterns` but it keeps telling me I'm rate-limited... hmm.)
- Logo PR merged

The next step will be transferring the repository and running spec-factory. I will work on that next week.

**Comment by ytlim696** [comment]
> Based on the discussion at the TPAC 2023 and follow ups, we’ll propose standardizing URLPattern API.
> 
> [URLPattern](https://wicg.github.io/urlpattern/) is the API providing a web platform primitive for matching URLs. The pattern syntax is adopted from the popular [path-to-regexp](https://github.com/pillarjs/path-to-regexp) javascript library and is more ergonomic than using regular expressions.
> 
> @jeremyroman and @sisidovski will edit the spec, who took over the work from @wanderview. 
> 
> Some questions to the sg:
> - @annevk suggested putting this proposal into the [URL workstream](https://whatwg.org/workstreams#url). Does that work for the rest of the SG?
> - Do we have anything to resolve on our side before moving to WHATWG?
> - Can we transfer the existing https://github.com/WICG/urlpattern repository into the WHATWG org?
> 
> For the short name, I feel just using “urlpattern” is fine. We suggest using a "*" in a circle as the icon.

**Comment by annevk** [comment]
Let's close this. Thanks everyone for getting this done!
