### ISSUE TITLE
Consider switching Code of Conduct and Working Mode to Markdown

### ISSUE THREAD

**Issue by othermaciej** [whatwg/sg#27]
Consider switching Code of Conduct and Working Mode to Markdown. We now have a conversion script to generate HTML suitable for publication on whatwg.org from our Markdown policies. Given this, it might be a good idea to write the two that are HTML into Markdown at some point, so we have have a consistent publication path.

**Comment by othermaciej** [comment]
We have a fully automated publication pipeline now. I'd like to change it so we don't need to modify the whatwg repo for each now policy, and then attempt to convert these.

**Comment by annevk** [comment]
Note that maybe https://whatwg.org/policies then also needs to be hosted here to enable linking to new policies, if any?

cc @domenic

**Comment by domenic** [comment]
Converting /policies seems fine; I don't see anything in that document that would require anything more advanced than Markdown.

(Side note: the numbered list seems like it should be a ul, not an ol, on that page. My bad I guess.)

I think working mode contains some HTML markup (such as `<p class="note">` or specific ID choices on each header) that won't be quite Markdown-able.

**Comment by annevk** [comment]
The main problem with converting policies might be the title / first header mismatch.

**Comment by othermaciej** [comment]
It seems ok to host the policies page here. If it needs a special case for its title that is doable.

**Comment by annevk** [comment]
When converting, please "upstream" the changes made (probably by just converting the documents in whatwg/whatwg.org instead):

* https://github.com/whatwg/whatwg.org/commits/master/whatwg.org/code-of-conduct
* https://github.com/whatwg/whatwg.org/commits/master/whatwg.org/working-mode

(The changes made should all be editorial.)

**Comment by annevk** [comment]
I'm not quite sure how to convert Working Mode to Markdown as it contains various classes annotate paragraphs as examples and such.

**Comment by domenic** [comment]
You should be able to still use HTML in those cases.

**Comment by othermaciej** [comment]
Markdown allows some embedded HTML but it limits which elements are allowed. I am pretty sure <p class> is supported.
