### ISSUE TITLE
SG Meeting: 2017-12-08, 10:00-11:00 Pacific time

### ISSUE THREAD

**Issue by othermaciej** [whatwg/sg#35]
Agenda

0. Choose someone to take minutes.
1. Review of actions from last meeting.
2. Editorial issues
	- Let's explicitly agree to a streamlined process <https://github.com/whatwg/sg/issues/28>
	- Assuming we agree, let's get quick review on Editorial Polish PRs: <https://github.com/whatwg/sg/pulls?q=is%3Aopen+is%3Apr+label%3A%22Editorial+Polish%22>
	- Some of these editorial polish issues are important for the HTML conversion script I wrote, to help Anne and Domemic set up a system to auto-publish HTML versions of the policies to whatwg.org: <https://github.com/MicrosoftEdge/taipei-walrus/pull/293>
3. Timeliness as per SG policy <https://github.com/whatwg/sg/issues/24>
	- Let's get a PR up and approve it.
4. SG chat room
	- It could be useful to have a chat room for quick realtime discussions where email or GitHub issue discussion is too clunky. For example, for quick requests for review on a PR or sign-off on an issue. This could also be handy for capturing minutes live.
	- WHATWG has a chat room on IRC, and W3C uses IRC channels for meetings. However, IRC is not super mobile friendly, and it's kind of old fashioned. 
	- An alternative would be to use Slack or Discord (chat services that have a good web-based interface as well as mobile apps).

**Comment by michaelchampion** [comment]
Minutes:

1. Choose someone to take minutes.
 - Informal agreement to rotate alphabetically by family name. @dbaron did the first one, so @michaelchampion will do this one.  Presumably @henceproved then @othermaciej will scribe the next meetings.

2. Review of actions from last meeting.

- Conclusion:  All have been completed

3. Editorial issues

 Let's  explicitly agree to a streamlined process #28
- Conclusion: All agreed that editorial changes just need one SG member to review and approve pull requests, no formal decision necessary

 Assuming we agree, let's get quick review on Editorial Polish PRs: https://github.com/whatwg/sg/pulls?q=is%3Aopen+is%3Apr+label%3A%22Editorial+Polish%22
- Discussion:
Do they need legal signoff?  The IPR policy and SG agreement still have section numbers; just the policy documents that don’t reference anything by section number.  So no legal review needed, need SG #34 closed before launch. 
- It is still unclear whether we should post  the PDF of the Steering Group Agreement with signatures and titles.  Not a launch blocker, wait to see if lawyers agree to publish names/titles/signatures
 
 Some of these editorial polish issues are important for the HTML conversion script Maciej wrote, to help Anne and Domemic set up a system to auto-publish HTML versions of the policies to whatwg.org: 
- Discussion:
The editors are still working on scripts that take documents in Markdown and then convert to HTML.  There was some pushback initially to this idea, but the scripts seem to work well and enable easier maintenance of documents in the SG repository.
 
3.  Timeliness as per SG policy #24
 Let's get a PR up and approve it. 
- Conclusion: **The SG agreed to resolve  #24 , and now DONE.**

4. SG chat room
 It could be useful to have a chat room for quick realtime discussions where email or GitHub issue discussion is too clunky. For example, for quick requests for review on a PR or sign-off on an issue. This could also be handy for capturing minutes live.
  WHATWG has a chat room on IRC, and W3C uses IRC channels for meetings. However, IRC is not super mobile friendly, and it's kind of old fashioned.
   An alternative would be to use Slack or Discord (chat services that have a good web-based interface as well as mobile apps).
- Discussion:
Agree that we need an easy venue for realtime requests and chat
Slack better than IRC – Shruthi working on setting up a channel
David – Slack imposes its own organization, so some would have lots of tabs open.  But no strong objections.
- Conclusion: The SG agreed to setup a Slack channel for this purpose.
