### ISSUE TITLE
Give guidance for copyright notice on translations in Workstream Policy

### ISSUE THREAD

**Issue by othermaciej** [whatwg/sg#40]
Some WHATWG specs link to translations into various languages. These are not official WHATWG Workstream products (I think), but because they are linked and implicitly endorsed, we should recommend an appropriate notice. Workstream Policy describes all the other notices, so that seems like a good place to do it.

According to CC BY recommendations, the right way to do it would be:

> This is a translation of X, which is licensed under a [Creative Commons Attribution 4.0 International License](https://creativecommons.org/licenses/by/4.0/). Copyright © 2017 WHATWG (Apple, Google, Mozilla, Microsoft).

Where X is the name of the Living Standard, marked up as a link to it.

**Comment by othermaciej** [comment]
I proposed policy text for the above suggestion in PR #59 

@henceproved @michaelchampion @dbaron I'd appreciate agreement or disagreement on this approach.

**Comment by henceproved** [comment]
I am good with this approach. Add me to the PR if it needs an additional review/LGTM (looks like the editors and lawyers had some comments/suggestions that were being discussed).
