### ISSUE TITLE
Consider making <h2> and <title>s of documents consistent with the rest of whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#44]
This is the normal relationship between these (illustrated with spec.whatwg.org):

* h2: Standards
* title: Web Hypertext Application Technology Working Group Standards

This is consistent for all documents introduced prior to the new policy documents.

This is what /ipr-policy does (and other newly introduced documents do similar things, though it varies):

* h2: The WHATWG Intellectual Property Rights Policy
* title: The WHATWG Intellectual Property Rights Policy

It would be more consistent to make that:

* h2: Intellectual Property Rights Policy
* title: Web Hypertext Application Technology Working Group Intellectual Property Rights Policy

(We could of course take this moment to bikeshed the rather long titles, though maybe that's best discussed separately given it doesn't just affect whatwg/sg documents. What I think is particularly important is that the h2 never says WHATWG as that is self-evident when viewing the document. The title pops up in other places where such context is not necessarily available and therefore it makes sense to have something like that there, although arguably with favicons there's a bit less of a need for that today.)

**Comment by annevk** [comment]
FWIW, I'd be happy with always writing WHATWG and only having the long version once somewhere. Super long titles are not really useful. Another thing we might want to consider is to put it at the end of the title, so the most significant bit is first.

**Comment by othermaciej** [comment]
I've proposed a PR to add the script to whatwg.org: https://github.com/whatwg/whatwg.org/pull/132

Once that lands, I think the issue should be moved there, since the most likely fix is in the script. In the Markdown source, we might want to consider removing "The" from the titles.

**Comment by annevk** [comment]
The Markdown source provides the h2, right? So you'd remove "The WHATWG ".

**Comment by othermaciej** [comment]
I'd rather have the script strip "The WHATWG". In Markdown form, the h2-level titles are the only titles. And it's kind of weird to leave out WHATWG in that context.

**Comment by annevk** [comment]
Looking at https://github.com/whatwg/sg/blob/master/Principles.md it does not seem too weird to me. It's pretty clear you're in WHATWG territory.

It's also less confusing I think as someone looking at both documents might think more is different if the headings don't match.

**Comment by othermaciej** [comment]
I'd like the the policy documents to have titles that make sense as a way to refer to them even outside the WHATWG context. Imagine someone is comparing how WHATWG works to how W3C works in an IETF meeting. We'd probably want them to say "The WHATWG IPR Policy is very similar to the W3C Patent Policy". It would be weird to just say "IPR Policy is very similar to the W3C Patent Policy". Now let's say someone asks if this will ever be changed to allow royalty-bearing RAND licensing. It would be appropriate to respond "We can't do that, it would be against the WHATWG Principles". It would a be a bit weird to say "We can't do that, it would be against the Principles", at least if that document hadn't come up in conversation already.

I think this is different than the case with Living Standards. It is fine and encouraged for people to refer to https://html.spec.whatwg.org as "HTML" or "The HTML Living Standard". There is no need to say "WHATWG". But policies are a bit different, I think.

Given this, I would like every presentation of the document to include an appropriately citable title. For the Markdown view in the repository, the top heading is the only form of the title available. So I think it should include "WHATWG". Yeah, people could guess that it is WHATWG related from the repo path, but we shouldn't make people guess the full title. The Markdown can also be copied outside the repo.

For the presentation in HTML form on whatwg.org, it's ok to put the full title only in `<title>`, and a shorter form in the `<h2>` level top header. I'm not entirely sure if it is better to do that, but it is reasonable to follow the site convention. Even if someone downloads the HTML form of the policy, they will still have the full title in `<title>`.

Given this, what I'd like to do is:
1. Add "WHATWG" to the title of "Principles" in Markdown form.
2. Take "The" off the start of the titles.
3. Make the conversion script include the full title in `<title>` and the shorter title (no "WHATWG") in `<h2>` in the HTML output.

Does this seem reasonable to everyone?

**Comment by henceproved** [comment]
>> Add "WHATWG" to the title of "Principles" in Markdown form.

I don't think this is necessary for Principles as it is for IPR policy, for instance. But, I like consistency and clarity, so +1.

Rest look reasonable. I agree with making these changes.

**Comment by annevk** [comment]
I don't quite agree, but I also don't think it's important as the website gets to be the way I proposed, so the resolution seems good.

**Comment by othermaciej** [comment]
Because this change will update the SG Agreement and Principles (though in a relatively trivial way), I'd appreciate unanimous sign-off from @dbaron @henceproved @michaelchampion on this. I will post a Pull Request and link it to this issue so the changes can be reviewed in context.

The script part will be handled by https://github.com/whatwg/whatwg.org/issues/147

**Comment by js-choi** [comment]
For what it’s worth, this and #55 make me wonder which, if either, is more correct in general speech: “The WHATWG is more than a decade old,” versus, “WHATWG is more than a decade old.”

**Comment by othermaciej** [comment]
@js-choi I think either form would be acceptable, as with W3C and IETF (though some other orgs like ECMA or ISO are never referred to with "The").

**Comment by othermaciej** [comment]
Script parto f this in https://github.com/whatwg/whatwg.org/pull/148

**Comment by domenic** [comment]
@js-choi I think when used as a noun it's "The WHATWG" and when used as an adjective (as in "WHATWG HTML Standard" or "WHATWG Principles") it's "WHATWG".
