### ISSUE TITLE
Notice for Living Standard supporting documents

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#48]
It's unclear how to change text documents carrying a notice, e.g., https://encoding.spec.whatwg.org/index-windows-1252.txt.

It's also unclear how to state the license for resource that themselves cannot carry one, e.g., https://encoding.spec.whatwg.org/encodings.json (JSON cannot include comments). (I have not checked in detail yet, but I suspect this also applies to a number of non-SVG images for the HTML Standard.)

**Comment by othermaciej** [comment]
For plain text formats that allow comments or non-material text, we can suggest a plain text form of the license text (with links replaced by spelled out URLs). Maybe it should also say something like "this is a supporting document for XXX (URL to XXX)".

For formats without a comment syntax, like JSON, it's trickier. Could we add a copyright notice to JSON as data, or is that likely to mess up consumers of the encodings file?

**Comment by annevk** [comment]
We could encode a comment as a string in the array I suppose. As far as I know none of this is consumed live so consumer code can be updated.

**Comment by domenic** [comment]
It seems nicer if supporting files could be covered by the statement in a nearby repository. After all there has to be some allowance for non-SVG images, and in that case it'd be ideal to use the same for data files like JSON and txt.

**Comment by othermaciej** [comment]
I've assumed that copyright notice in the linking spec and nearby in the repository is sufficient, both for images and for text-based formats. For text files that may get downloaded and embedded into software (as is the intent of encodings.json), an inline notice is potentially helpful. So we may as well provide for one if it's not too much hassle.

**Comment by othermaciej** [comment]
@annevk since Encodings is most affected, what are your thoughts? Would you rather have a recommended plaintext form of the copyright notice for plain text supporting documents, or just rely on the copyright that's in the repository and on the linking Living Standard? I can draft up a PR against Workstream Policy for either approach.

**Comment by annevk** [comment]
I'd rather rely on linking as that works for all subresources (of any type) across all standards.

**Comment by othermaciej** [comment]
OK. In that case, I think it would be best to update the Workstream Policy to state that inline copyright notices aren't needed for supplemental resources for a Living Standard, whether linked or embedded.

**Comment by annevk** [comment]
Can @dbaron @henceproved @michaelchampion please comment on https://github.com/whatwg/sg/issues/48#issuecomment-352090710? It's blocking an update to the Encoding Standard.

**Comment by henceproved** [comment]
So, supplemental resources, of any kind, do not require inline copyright notices and will rely on the copyright notice on the linking Living Standard? That sounds fine to me.

**Comment by michaelchampion** [comment]
That sounds OK to me too

**Comment by dbaron** [comment]
Yeah, I'm ok with that update.

Would it still be good practice to package (e.g., in a zip, or in a directory) those files in a way that has the license in a separate file so that it will tend to stay next to them?

**Comment by annevk** [comment]
@dbaron the current state is https://encoding.spec.whatwg.org/index-windows-1252.txt and https://encoding.spec.whatwg.org/encodings.json. The GitHub repository will contain a LICENSE resource, but there's not really any packaging or directory grouping going on.

**Comment by othermaciej** [comment]
I believe pull request #58 reflects the consensus in this issue.
