### ISSUE TITLE
Appoint Philip Jägenstedt as the editor for Fullscreen

### ISSUE THREAD

**Issue by othermaciej** [whatwg/sg#61]
The current editor is Anne van Kesteren. Both Philip and Anne support this change, and have proposed a PR to update the Workstream list:  #60 

I support this change. In the PR, @dbaron said he supports as well.

@henceproved and @michaelchampion do you approve?

(Making this an issue and not just a PR so we can follow the letter of the SG Policy, which says to record decisions in an issue).

**Comment by henceproved** [comment]
I support this change.

**Comment by michaelchampion** [comment]
I support this change

**Comment by foolip** [comment]
That's all of you, thanks for your support! If someone can merge the PR, I will take care of the rest.
