### ISSUE TITLE
code-of-conduct and working-mode out-of-date

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#68]
Since this repository is currently not the canonical place for code-of-conduct and working-mode, despite everyone's wishes, they have gone out-of-date with their whatwg/whatwg.org counterparts.

As you can see from

* https://github.com/whatwg/whatwg.org/commits/master/whatwg.org/code-of-conduct
* https://github.com/whatwg/whatwg.org/commits/master/whatwg.org/working-mode

the changes made to them have been editorial in nature. It'd still be good to rectify this situation somehow of course.

**Comment by domenic** [comment]
#27 is the plan of record, I think?

**Comment by annevk** [comment]
Thanks, added a comment there. Let's close this.
