### ISSUE TITLE
Publish Workstreams.md on whatwg.org

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#75]
It's not clear to me why this document is published on GitHub. Is it because we still want to centralize the data source for this?

**Comment by domenic** [comment]
Yeah, I think this is https://github.com/whatwg/meta/issues/57. Note the bullet

> Either merge Workstreams.md and spec.whatwg.org into a new spec.whatwg.org, or generate two of them

**Comment by othermaciej** [comment]
I'd like it if we could  publish from this repo into specs.whatwg.org. Maybe the MarkDown conververter could be taught to do this? It makes sense for whatwg.org to host the official Workstream list.

**Comment by annevk** [comment]
Is it okay if the SG maintains a JSON resource that encodes all this data which is converted into something publishable upon changes? (And yeah, those changes being reflected upon spec.whatwg.org is doable as that is part of the whatwg/whatwg.org repository.)

I suppose we could find some way to encode all the information in https://github.com/whatwg/meta/issues/57 in Markdown somehow, but it doesn't seem ideal.

**Comment by foolip** [comment]
Generating from a JSON resource file sounds good, it would be similar to the current markdown conversion.

**Comment by annevk** [comment]
https://github.com/whatwg/sg/pull/111 and https://github.com/whatwg/whatwg.org/pull/303 are my attempt at solving this.
