### ISSUE TITLE
Editorial: .md document footers are inconsistent with the rest of the site

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#78]
In particular, they don't use `<footer>`. I'd suggest fixing this after #27.

**Comment by annevk** [comment]
And they do include `<hr>`, which should probably be dropped.

**Comment by othermaciej** [comment]
I think I tried to use <footer> and found that I could not, due to limitations in GitHub Markdown. Would be glad to try again. Or the conversion script can do a rewrite.

**Comment by henceproved** [comment]
Is this still an open issue? Did we figure out what the action on this needs to be?

**Comment by domenic** [comment]
I think we can fix this on the conversion script side, most likely.

**Comment by henceproved** [comment]
Great! Anything the SG needs to be involved in, or should we close this issue?

**Comment by domenic** [comment]
I think it'll probably eventually involve SG signoff on some PRs to those documents, but they will be fairly editorial. It'd probably be good to keep this open for tracking purposes though.

**Comment by annevk** [comment]
One other inconsistency I noticed is that `rel=license` is not there due to Markdown's limited capabilities. We could add this on the `whatwg.org` side through a script I suppose.
