### ISSUE TITLE
Joining the SG

### ISSUE THREAD

**Issue by edent** [whatwg/sg#80]
I am interested in understanding how my organisation can join the Steering Group.

As per https://github.com/whatwg/meta/issues/87

**Comment by othermaciej** [comment]
What's the organization, and are they a Qualifying Entity per the SG Agreement?

**Comment by henceproved** [comment]
We haven't received a response with details about the organization and whether it is a Qualifying Entity, so closing this issue. But, please do re-open with specifics, if this is something you are still interested in exploring.
