### ISSUE TITLE
Commit by Baidu, Inc employee to the HTML Standard

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#82]
I accidentally approved @harttle's https://github.com/whatwg/html/commit/3876e4b75cd9f9b048779a70831027c6e9c61813 not realizing they work for Baidu, Inc despite that being clearly advertised.

I think there's two questions here.

One for @harttle: could you get Baidu, Inc to sign https://participate.whatwg.org/agreement as an Entity?

One for the SG: what I should do with the above commit (this relates to #63)?

**Comment by harttle** [comment]
> could you get Baidu, Inc to sign https://participate.whatwg.org/agreement as an Entity?

OK. I'm working on it. Though I do not care about this, why "those who work in the field of web technologies as an employee" **must** have that Agreement executed by a representative of that Entity?

**Comment by annevk** [comment]
@harttle in a word, patents. https://whatwg.org/ipr-policy has more details. Hope that helps and sorry for not communicating this clearly at the time you made the PR.

**Comment by othermaciej** [comment]
I'll get other SG members to weigh in, but in the meantime, my personal opinion is that the right action would be to revert until/unless the Entity agreement is executed.

**Comment by harttle** [comment]
> until/unless the Entity agreement is executed.

Update: We're working on it these days and it will work out soon.

**Comment by harttle** [comment]
It's done, added me and @errorrik as contacts. See https://github.com/whatwg/participant-data/commit/a81535c39fd898f9a494cc08ead48d2fd8c946d4

**Comment by othermaciej** [comment]
There's no IPR issue with the commit now, so I think no SG action or decision is necessary.

**Comment by domenic** [comment]
Yay, thank you @harttle for pursuing this!!

**Comment by harttle** [comment]
@domenic you helped me out [the first commit](https://github.com/whatwg/html/issues/2736), this is actually the second one. Thank you guys!
