### ISSUE TITLE
Memorandum of Understanding with the W3C

### ISSUE THREAD

**Issue by henceproved** [whatwg/sg#90]
This issue is filed for the steering group to vote on the Memorandum of Understanding with the W3C ([draft](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html)).

As per the [SG policy](https://github.com/whatwg/sg/blob/master/SG%20Policy.md#decisions), all steering group decisions with a visible public effect, as well as the consensus from SG reps, must be recorded in a github issue in this repository.

**Comment by henceproved** [comment]
I vote in favor of this MoU.

**Comment by othermaciej** [comment]
I vote in favor of this MoU.

**Comment by michaelchampion** [comment]
I vote in favor of this  MoU

**Comment by dbaron** [comment]
I vote in favor of this MoU.

**Comment by henceproved** [comment]
I vote in favor of this MoU, and that's all four votes from the WHAWTG steering group!

**Comment by Aquariu10** [comment]
> This issue is filed for the steering group to vote on the Memorandum of Understanding with the W3C ([draft](https://www.w3.org/2019/04/WHATWG-W3C-MOU.html)).
> 
> As per the [SG policy](https://github.com/whatwg/sg/blob/master/SG%20Policy.md#decisions), all steering group decisions with a visible public effect, as well as the consensus from SG reps, must be recorded in a github issue in this repository.
