### ISSUE TITLE
Circular reference in the WHATWG IPR policy / bug in the contribution license

### ISSUE THREAD

**Issue by frivoal** [whatwg/sg#95]
Section [5.2. Contribution Licensing Obligations](https://whatwg.org/ipr-policy#52-contribution-licensing-obligations) consists of the following text (emphasis mine):

> For each Contribution, the **_Contribution Licensing Obligations_** are effective irrevocably on the 45th Day after the Contribution was first made.

The part emphasized is a link, a circular reference back that same sections' title. This fails to achieve the intended effect, which was to say what kind of obligations are effective on the 45th day.

I believe that instead, the text of that link was intended to be "Patent Licensing Obligation", and to link to [2.6. "Patent Licensing Obligation"](https://whatwg.org/ipr-policy#26-patent-licensing-obligation)

**Comment by TimothyGu** [comment]
Hmm, I don't think so. Patent-Licensing Obligations have two subtypes, as shown in https://whatwg.org/ipr-policy#51-patent-licensing-obligations-in-general, which defines what "Contribution Licensing Obligations" and "Review Draft Licensing Obligations" mean. Section 5.2 deals with the former type in particular.

**Comment by dbaron** [comment]
Would it clarify things if "Contribution Licensing Obligations" in 5.2 and "Review Draft Licensing Obligations" in 5.3 linked back to 5.1 rather than to their own sections?  Or perhaps if they weren't links at all?

**Comment by TimothyGu** [comment]
IMO the “(the "Contribution Licensing Obligations")” and “(the "Review Draft Licensing Obligations")” should be marked as definitions. That would certainly help with the flow.

**Comment by annevk** [comment]
I put up a proposal for this in #161, largely following @TimothyGu's suggestion.
