### ISSUE TITLE
Splitting off WebSockets into a separate standard

### ISSUE THREAD

**Issue by ricea** [whatwg/sg#97]
I'd like to create a new standard for WebSockets, and move the WebSocket content currently at   https://html.spec.whatwg.org/multipage/web-sockets.html and https://fetch.spec.whatwg.org/#websocket-protocol into it.

There are two main reasons for doing this:
1. It will reduce the number of standards for WebSockets from 3 to 2.
2. It will make it easier to integrate a new API to support backpressure.

**Comment by dbaron** [comment]
cc editors of HTML (@domenic) and fetch (@annevk)

**Comment by domenic** [comment]
Works for me. I very much trust @ricea here given the excellent work he's done on Streams.

**Comment by domenic** [comment]
I should mention that the main question for the SG would be whether this should be a new workstream, or a new standard in the HTML workstream, or perhaps even a new standard in the Fetch workstream. The vast majority of the text and concepts would come from HTML, so my initial instinct was as another spec in the HTML Workstream.

**Comment by henceproved** [comment]
A spec in the HTML workstream is my first instinct as well.

**Comment by michaelchampion** [comment]
Agree, why do we need a whole new workstream?

**Comment by annevk** [comment]
I think this would be good. Making it part of the HTML Workstream would be the easiest I think. For context, when @ricea, @domenic, and I discussed this in person we weren't sure whether taking some text from Fetch would be considered problematic. It's not that much text though and in the end Fetch would still have some mentions of WebSockets as not everything can be taken out.

**Comment by othermaciej** [comment]
If done as a new spec in the same work stream, I think it would be our first case of multiple specs per Workstream. We should make sure everything is technically set up to do it that way, if that's what we want. For example, if it's two separate repos and we have a technical check on PRs, it would have to apply to both. If it's one PR, we would have to make sure Review Draft publication affects both. Another thing worth noting is that each Workstream has exactly one Editor (though they may appoint deputy editors that are authorized to edit).

I am ok with either approach. As far as process technicalities, if it's a new document in an existing Workstream, that falls under [Editor Discretion](https://whatwg.org/workstream-policy#editor-discretion):

> The Workstream's Editor may add, remove, merge or split Living Standards and other associated documents, so long as all deliverables are still within the Workstream's Scope. If the change affects Living Standards, the Editor must notify the Steering Group 14 Days in advance of the change.

So all that would be required is 14 days advance notice to the Steering Group.

For a new Workstream, the somewhat more elaborate [New Workstreams process](https://whatwg.org/workstream-policy#new-workstreams) applies. This would require a Workstream Proposal.


That said, I don't believe either of these processes has been exercised before. If we find a problem when attempting to do either of these things, the SG can amend the process, if needed.

**Comment by zcorpan** [comment]
@othermaciej it is under Editor Discretion to move the parts in HTML to a separate spec in the same workstream, but not for moving the Fetch parts to the HTML workstream, correct?

**Comment by hober** [comment]
> If done as a new spec in the same work stream, I think it would be our first case of multiple specs per Workstream.

IIRC Fetch and XHR are in the same Workstream.

**Comment by othermaciej** [comment]
> IIRC Fetch and XHR are in the same Workstream.

I recall this being discussed, but that's not where we ended up. The [master Workstream list](https://github.com/whatwg/sg/blob/master/Workstreams.md) has them as separate.

**Comment by othermaciej** [comment]
> @othermaciej it is under Editor Discretion to move the parts in HTML to a separate spec in the same workstream, but not for moving the Fetch parts to the HTML workstream, correct?

I guess it's a matter of interpretation. My view is that as long as the change does not materially change the scope of the HTML Workstream or the Fetch Workstream, and is allowed by the license, and both editors agree, it's editor's discretion. The way I see it, if it would be ok to delete the text from Fetch, then contribute the same text to HTML, it's ok to move text.

Somewhat oddly, the Workstream Policy does not address the case of moving content from one Workstream to another, even though in retrospect it is a likely and commonplace activity. It might be worth spelling it out explicitly.

**Comment by domenic** [comment]
> The way I see it, if it would be ok to delete the text from Fetch, then contribute the same text to HTML, it's ok to move text.

This is a fair point, and I think the text in question definitely meets that bar.

**Comment by dwsinger** [comment]
> The way I see it, if it would be ok to delete the text from Fetch, then contribute the same text to HTML, it's ok to move text.

Doesn't it depend on who Contributed the original text (this may be plural), and who Contributes that text to the new WS?

**Comment by othermaciej** [comment]
So in summary, in the case of "spec split in the HTML workstream", @domenic should officially notify the SG (I  think a comment in this issue would do) to start the 14-day clock. In the case of "new workstream", someone would have to provide the info requested for a Workstream Proposal and then the various process steps happen, including SG decision.

**Comment by othermaciej** [comment]
> Doesn't it depend on who Contributed the original text (this may be plural), and who Contributes that text to the new WS?

For contributions before the modern WHATWG governance system, it doesn't make a difference.

Under the modern system, we might need to consult lawyers. My not-a-lawyer read is that contribution copyright grants still stand, review draft patent grants would apply at the next review draft, and for contribution patent grants, I am not sure. To be extra cautious, we could check whether anything was contributed to the WebSockets portion of Fetch by anyone who is not a pariticipant in the HTML Workstream after the start of the new IPR policy.

**Comment by domenic** [comment]
> So in summary, in the case of "spec split in the HTML workstream", @domenic should officially notify the SG (I think a comment in this issue would do) to start the 14-day clock. 

Make it so! (I.e., I am officially notifying the SG that we'd like to do such a spec split in the HTML Workstream.)

**Comment by dbaron** [comment]
We'd be interested in learning a bit about the material that would be moving from the fetch workstream to the HTML workstream.  In particular:
* approximately what material do you expect to move?
* do you know who initially contributed it?
* do you know whether that contribution happened before or after the WHATWG's IPR policy went into effect on 2018-01-11 (January 11, 2018)?

**Comment by annevk** [comment]
I would expect https://fetch.spec.whatwg.org/#websocket-protocol to move, which I contributed, before the policy went into effect. I don't immediately see a way for the other places where Fetch deals with WebSocket to reasonably be moved (but they're also minor).

Here's a list of all commits that mention WebSocket in a case-insensitive (per whatever `-i` rules are) fashion:
```
commit e26376910a3f1b230177104759de8fcf33a02f2e
Author: Gary Blackwood <gary@garyblackwood.co.uk>
Date:   Thu Dec 13 09:05:56 2018 +0000

    Use forgiving-base64 encode on WebSocket's keyValue
    
    This improves the consistency of the document by referencing the same type of base64-encoding throughout. Also isomorphic encode it as base64 encoding returns a string.
    
    Fixes #712.

commit 8b070f14a1fb2d1f8f4d07e1902a40a14f77b060
Author: Adam Rice <ricea@chromium.org>
Date:   Sat Jun 16 23:40:25 2018 +0900

    Stop saying HTTP authentication over WebSocket is disallowed
    
    Closes #565. Follow-up: #766.

commit 60db35ed0d18c6636f002da91593bfa5ee58494e
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Fri Nov 17 16:07:59 2017 +0100

    WebSocket handshake has no referrer
    
    Tests: https://github.com/w3c/web-platform-tests/pull/8280.
    
    Fixes #630.

commit 34027b618090e381c398cac7896fa8362ee4bb9c
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Tue Oct 10 12:25:16 2017 +0200

    Reference correct RFC for The WebSocket Protocol
    
    Fixes #613.

commit 406c5a60595c63d323693050b45d40823933e185
Author: Anthony Ramine <n.oxyde@gmail.com>
Date:   Mon Mar 27 13:35:48 2017 +0200

    Properly set the Origin header for WebSocket requests

commit ef3f184a60227109e75c0c45feb51227408de61c
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Fri Mar 10 19:16:13 2017 +0100

    Meta: remove for=websocket
    
    Fixes #500.

commit 267a8effeacfe5d641010d1d4f4609f9602cdab6
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Mon Mar 14 10:19:19 2016 +0100

    Define permessage-deflate extension and cache-mode for WebSocket
    
    Fixes #247.
    
    (This commit also adds a LICENSE resource, to more clearly document
    the policy of this repository.)

commit 08f8560f6cecaedc1c3372f9fff1ee39c3bfc86f
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Thu Mar 10 16:48:57 2016 +0100

    Define the WebSocket subprotocol check as part of response validation
    
    See https://github.com/whatwg/html/pull/840#discussion_r55568720 for discussion and context. Many
    thanks to Simon Pieters for helping out.

commit eb07418c8383983a9887498e49a2e2e986d3c9f4
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Thu Mar 10 13:08:15 2016 +0100

    Define port blocking
    
    See https://github.com/whatwg/html/issues/841 for context. Apparently
    this was introduced by Doug Turner in the Netscape days to fix a
    security hole. Other browsers copied it and Apple made six additions
    to account for what is presumably internal usage and IRC. Gecko has
    not copied those additions, but Chrome has, so I'm including them
    here.
    
    Since all of networking needs this the special casing in the
    WebSocket API can now be removed.
    
    Took a little less than fifteen years for this to get standardized.
    Hurray! 🎉

commit f3e1da80e141cf2c92ba921ed07873ea726cf9a9
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Thu Mar 10 09:35:07 2016 +0100

    Fix #240: one more WebSocket nit

commit a8392d0933ea7d771ed86acd4734e735eb81e8ac
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Wed Mar 9 15:47:45 2016 +0100

    Fix #238: excellent WebSocket nits

commit ce16adc5c13b56b0f8a6487c71fb030a9bccafce
Author: Anne van Kesteren <annevk@annevk.nl>
Date:   Mon Mar 7 15:54:02 2016 +0100

    Define the WebSocket client handshake in terms of Fetch
    
    Fixes #235.
```

**Comment by travisleithead** [comment]
Thanks @annevk. So, for contributions following 2018-01-11, we have 2. Gary [is a member of all workstreams](https://github.com/whatwg/participant-data/blob/master/individuals.json), so his contribution should flow just fine. Adam is covered by Google, and Google [participates in both html and fetch workstreams](https://github.com/whatwg/participant-data/blob/master/entities.json), so this contribution should be fine to move AFAICT. Of course, I'd imagine we'll need to have the specific content that gets moved once the PR is ready to know the extent of any relevant contributions. I imagine there's a way to collect a history of contributions per affected lines of code which could be used as a final check if we want to be extra careful.

**Comment by dbaron** [comment]
Sorry for letting this response take so long.  We're fine with this particular change happening; it sounds like it's an improvement in terms of the organization of WebSockets, and the IPR issues appear to be fine in this case.

In general, we would like to have a chance to look at cases where text is going to be moved between workstreams, although we hope to give a faster response in the future now that we've had a chance to consider this sort of issue.

-David, on behalf of the SG

**Comment by foolip** [comment]
Is there an issue for implementing this?

**Comment by annevk** [comment]
Not yet, once @ricea is ready to go through with this let's discuss the details on https://github.com/whatwg/meta?

**Comment by GPHemsley** [comment]
whatwg/meta#202
