### ISSUE TITLE
Working Mode: clarify that "Changes" is asynchronous and subject to appeal

### ISSUE THREAD

**Issue by annevk** [whatwg/sg#98]
https://whatwg.org/working-mode#changes is not as clear as it could be that major changes are best not announced and committed to master within a day or so. Some time should pass for review and appeal to ensure the broadest possible buy-in while still moving relatively quickly.

Maybe a third bullet point could be added to the second list saying something to the effect of:

* For major changes enough time should have passed for review and appeal by the larger community. Generally a full week is considered sufficient.

(Generally I measure this from the time an issue or PR is opened to the time where the PR could land on master.)

**Comment by domenic** [comment]
Nit, I'd put this in the first list, as the second list is about mechanical criteria. Probably right after "It should have been reviewed by one or more members of the community."
