### ISSUE TITLE
Working Mode: describe "don't write fiction" rule as joint responsibility of editor and implementers

### ISSUE THREAD

**Issue by dbaron** [whatwg/sg#99]
I made this comment on a draft of a different charter, and @hober pointed out the wording I was commenting on came from the WHATWG working mode, where I think it applies equally.

Currently, the working mode says:

> The editor has the following responsibilities, all of which can be delegated to deputy editors:
> 
> * Ensure any applied changes fulfill the relevant criteria for changes.
> * Resolve conflicts between contributors.
> * Reduce open issues.
> * Help manage the corresponding tests.
> * Ensure implementations follow the standard and vice versa. (The “don’t write fiction” rule.) 

I think the last of these is a little bit different from the first four, because the first four are things that the editor can really be expected to be fully responsible for.  The last one, however, can't be done without the participation of implementers.  For example, when implementers choose not to follow the specification, they need to tell the editor about it (file issues) rather than just silently do something else.  Likewise implementers have some responsibility to review the specification to check that what the editor has written matches those implementations -- and editors also have some responsibility to solicit/extract this review from implementers.

So my suggested wording change was just the addition of a parenthetical:

> * Ensure (together with implementers) that implementations follow the standard and vice versa. (The “don’t write fiction” rule.) 

although I'm sure there are better ways to word this.

**Comment by annevk** [comment]
In part I would expect editors to be involved with writing tests and also write tests themselves and run these against browsers. I don't think any of the first four points really captures that.

The system is complex enough that a single person cannot track all of it, so perhaps we ought to mention that other folks also carry a responsibility there, but I do think it's part of the role to some extent.

**Comment by domenic** [comment]
I think perhaps the problematic part here comes from the way this bullet is doing two things at once with "vice versa". In particular:

- Ensure that implementations follow the standard: mostly the responsibility of implementers, although editors have a role to play in e.g. filing bugs, ensuring tests are written and implementers are aware of them, etc.
- Ensure that the standard "follows implementations": this refers to the responsibility of editors to only write new things which have implementer interest and can work with the architecture of current implementations, and to continually align existing things with implementations by e.g. removing things from the standard as they are removed from implementations, or checking in to make sure implementer "interest" doesn't go too long without turning into actual implementations (e.g. https://github.com/whatwg/html/issues/4937), and so on.

Maybe disentangling these would help.

**Comment by annevk** [comment]
I think I would live with the short version, but the long version seems quite valuable as well and perhaps we should go with that as clarity is more important than brevity here.

**Comment by michaelchampion** [comment]
Should the "more concretely" bullets say anything about use in websites or interest from major website developers as well as "implementers?" Or does "implementer" imply both browser platform developers and website / webapp / framework developers?

It would be good to make the success criteria clear, but I don't have a strong opinion on whether this is the right place to state them. Nor am I convinced there is a real problem with features that get implemented in browsers but not used on the web; I worked on a browser team long enough to appreciate that they (now anyway) pay attention to user-side demand before investing in supplying a platform implementation.

Nevertheless, an implemented platform feature that gets very little use in the wild seems  "fictional" to me.  Maybe the simplest change to reflect my concern would be something like:

> Align existing features with implementations (e.g., via removal if implementer interest waned)

to "Align existing features with those actually implemented and used on the web (e.g., via removal if implementer interest waned or web developers don't adopt them)."

**Comment by annevk** [comment]
Yeah, that might make sense. Adoption (or type of adoption, if a feature has many facets) is definitely something editors look at, though often with help from implementers or those that know how to query HTTP Archive effectively (hi zcorpan).

**Comment by othermaciej** [comment]
In a PR for this issue, Anne proposed this expansion, which somewhat covers the points in comments above:

> * Ensure implementations follow the standard and vice versa. (The “don’t write fiction” rule.) More concretely:
>    * Ensure implementation bugs have been filed.
>    * Ensure the standard has test coverage.
>    * Only add features that have sufficient implementer interest.
>    * Align existing features with implementations (e.g., via removal if implementer interest waned).
